config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "products#index"
  
  resources :parts
  resources :products do
    member do
      get :pdf
    end
    resources :part_products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
# frozen_string_literal: true

class Brand < ApplicationRecord
  has_many :parts
  has_many :products
end

app/models/part.rb
# frozen_string_literal: true

class Part < ApplicationRecord
  has_one_attached :image

  def image_path
    image.service.path_for(image.key)
  end
end

app/models/part_product.rb
# frozen_string_literal: true

class PartProduct < ApplicationRecord
  belongs_to :part
  belongs_to :product
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :part_products
  has_many :parts, through: :part_products

  has_one_attached :pdf_cache

  def pdf
    (pdf_cache.presence || pdf_render).download
  end

  def pdf
    Pdf.render('app/views/products/show.pdf.erb', product: self)
  end

  private

  def pdf_render
    pdf_cache.attach(
      io: StringIO.new(Pdf.render('app/views/products/show.pdf.erb', product: self)),
      filename: "#{name}.pdf"
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/part_products_controller.rb
class PartProductsController < ApplicationController
  def new
    @part_product = PartProduct.new(product: product)
    @parts = Part.order(:name).pluck(:name, :id)
  end
  
  def create
    product.part_products.create!(part_product_params)

    redirect_to edit_product_path(product)
  end
  
  def edit
    product
    part_product
    @parts = Part.order(:name).pluck(:name, :id)
  end

  def update
    part_product.update!(part_product_params)

    redirect_to edit_product_path(product)
  end
  
  def destroy
    part_product.destroy!

    redirect_to edit_product_path(product)
  end

  private

  def part_product
    @part_product ||= PartProduct.find(params[:id])
  end

  def product
    @product ||= Product.find(params[:product_id])
  end

  def part_product_params
    params.require(:part_product).permit(:amount, :part_id)
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  def index
    @parts = Part.order(:name)
  end

  def new
    @part = Part.new
  end

  def create
    part = Part.create!(part_params)

    if part.image.blank? && params[:part][:image_url].present?
      uri = URI(params[:part][:image_url])
      file = Net::HTTP.get(uri)

      part.image.attach(io: StringIO.new(file), filename: uri.path.slice(/[^\/]+\z/)) 
    end

    redirect_to parts_path
  end

  def edit
    part
  end

  def update
    part.update!(part_params)

    redirect_to parts_path
  end
  
  def destroy
    part.destroy!

    redirect_to parts_path
  end

  private

  def part
    @part ||= Part.find(params[:id])
  end

  def part_params
    params.require(:part).permit(:brand_name, :name, :image)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.order(:name)
  end

  def show
    respond_to do |format|
      format.pdf do
        send_data(
          product.pdf,
          filename: "#{product.name}.pdf",
          disposition: 'inline',
          type: 'application/pdf'
        )
      end

      format.html do
        render :show, locals: { product: product }
      end
    end
  end

  def edit
    @part_products = product.part_products.includes(:part)
  end

  def update; end

  def destroy
    @product.destroy!

    redirect_to products_path
  end

  private

  def product
    @product ||= Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title>Speelotheek</title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="p-3 mb-3 border-bottom">
      <div class="container-fluid">
        <ul class="nav">
          <li class="col-2">
            <%= link_to("Producten", products_path) %>
          </li>
          <li class="col-2">
            <%= link_to("Onderdelen", parts_path) %>
          </li>
        </ul>
      </div>
    </header>

    <%= yield %>
  </body>
</html>

app/views/part_products/_form.html.erb
<%= form_for([@product, @part_product]) do |form| %>
  <%= form.label :amount %>
  <%= form.number_field :amount %>
  
  <%= form.label :part %>
  <%= form.select :part_id, @parts %>
  
  <%= form.submit %>
<% end %>

app/views/part_products/edit.html.erb
<div>
  <h1><%= link_to(@product.name, edit_product_path(@product)) + " > " + @part_product.part.name %></h1>
</div>

<%= render partial: "form" %>

app/views/part_products/new.html.erb
<div>
  <h1><%= link_to(@product.name, edit_product_path(@product)) + " > nieuw onderdeel" %></h1>
</div>

<%= render partial: "form" %>

app/views/parts/_form.html.erb
<%= form_for @part do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :brand_name, class: "form-label" %>
    <%= form.text_field :brand_name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :image, class: "form-label" %>
    <%= form.file_field :image, accept:"image/*", capture: "environment", class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :image_url, class: "form-label" %>
    <%= form.text_field :image_url, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

<video autoplay></video>

<script type="text/javascript">
  const constraints = {
    video: true,
    facingMode: "environment"
  };

  const video = document.querySelector("video");

  // navigator.mediaDevices.getUserMedia(constraints).then((stream) => {
  //   video.srcObject = stream;
  // });
</script>

app/views/parts/edit.html.erb
<h1><%= @part.name %></h1>

<%= render partial: "form" %>

app/views/parts/index.html.erb
<h3><%= link_to("Nieuw onderdeel", new_part_path) %></h3>

<div class="container">
  
</div>
<table>
  <thead>
    <tr>
      <th></th>
      <th>Naam</th>
      <th>Merk</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%- @parts.each do |part| %>
      <tr>
        <td style="height: 40px">
          <%- if part.image.present? %>
            <img src=<%= url_for(part.image) %> alt=<%= part.name %> style="max-height: 40px"/>
          <%- end %>
        </td>
        <td><%= link_to(part.name, edit_part_path(part)) %></td>
        <td><%= part.brand_name %></td>
        <td><%= link_to("Verwijder", part_path(part), method: :delete) %></td>
      </tr>
    <%- end %>
  </tbody>
</table>

app/views/parts/new.html.erb
<h1>Nieuw onderdeel</h1>

<%= render partial: "form" %>

app/views/products/edit.html.erb
<div>
  <h1><%= link_to("Lijst", products_path) + " > " + @product.code  + "-" + @product.name %></h1>
</div>

<h3><%= link_to("Nieuw onderdeel", new_product_part_product_path(@product)) %></h3>

<table>
  <thead>
    <tr>
      <th>Aantal</th>
      <th></th>
      <th>Naam</th>
    </tr>
  </thead>
  <tbody>
    <%- @part_products.each do |part_product| %>
      <tr>
        <td><%= part_product.amount %></td>
        <td><img src=<%= url_for(part_product.part.image) %> alt=<%= part_product.part.name %> style="max-height: 40px"</td>
        <td><%= link_to(part_product.part.name, edit_product_part_product_path(@product, part_product)) %></td>
      </tr>
    <%- end %>
  </tbody>
</table>

app/views/products/index.html.erb
<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Naam</th>
    </tr>
  </thead>
  <tbody>
    <%- @products.each do |product| %>
      <tr>
        <td><%= product.code %></td>
        <td><%= link_to(product.name, edit_product_path(product)) %></td>
      </tr>
    <%- end %>
  </tbody>
</table>

app/views/products/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <style>
      .flex-container {
        display: flex;
        flex-flow: row wrap;
        background-color: Blue;
      }
      div.part {
        height: 2cm;
        width: 6cm;
        border: 1px solid black;
        background-color: Red;
      }
      div.part > div.image {
        height: 2cm;
        width: 2cm;
        float: left;
        background-color: Green;
      }
      div.part > div.image > img {
        max-height: 2cm;
        max-width: 2cm;
        vertical-align: middle;
      }
      div.part > div.image > span.helper {
        display: inline-block;
        height: 100%;
        vertical-align: middle;
      }
      div.part > div.description {
        height: 2cm;
        width: 3.8cm;
        float: right;
        background-color: Yellow;
      }
    </style>
  </head>
  <body>
    <h3><%= "#{product.code} Tellijst #{product.brand_name} #{product.name}" %></h3>

    <div class="flex-container">
      <% product.part_products.each do |part_product| %>
        <div class="part">
          <div class="image">
            <span class="helper"></span>
            <!-- <img src="<%= "data:image/png;base64,#{Base64.strict_encode64(part_product.part.image.download)}" %>" alt=<%= part_product.part.name %>> -->
          </div>
          <div class="description">
            <%= "#{part_product.amount} #{part_product.part.name}" %>
          </div>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/products/show.pdf.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <style>
      .flex-container {
        display: flex;
        flex-flow: row wrap;
        background-color: Blue;
      }
      div.part {
        height: 2.2cm;
        width: 6.6cm;
        border: 1px solid black;
        display: flex;
        align-content: center;
        background-color: Red;
      }
      div.part > div.image {
        height: 2.2cm;
        width: 2.2cm;
        background-color: Green;
      }
      div.part > div.image > img {
        max-height: 2cm;
        max-width: 2cm;
        vertical-align: middle;
      }
      div.part > div.description {
        height: 2cm;
        width: 3.8cm;
        background-color: Yellow;
      }
    </style>
  </head>
  <body>
    <h3><%= "#{product.code} Tellijst #{product.brand_name} #{product.name}" %></h3>

    <div class="flex-container">
      <% product.part_products.each do |part_product| %>
        <div class="part">
          <div class="image">
            <span class="helper"></span>
            <img src="<%= "data:#{part_product.part.image.content_type};base64,#{Base64.strict_encode64(part_product.part.image.download)}" %>" alt=<%= part_product.part.name %>>
          </div>
          <div class="description">
            <%= "#{part_product.amount} #{part_product.part.name}" %>
          </div>
        </div>
      <% end %>
    </div>
  </body>
</html>